### ISSUE TITLE
Overscroll after end of program

### ISSUE THREAD

**Issue by Yohe-Am** [zifeo/whiz#115]
Not sure what causes this as it only occurs in certain scenarios but observe the following gif at the start of which I'd just "reloaded" the pane:

![Recording 2024-01-23 at 03 32 16](https://github.com/zifeo/whiz/assets/56622350/5c19f9bf-15bb-4f43-ab70-f5be8d94c8cb)

The blank output you see afterwards is the overscroll and I have to page-up multiple times to return to the actual end of output.

whiz.yaml doesn't contain anything exotic and is shown here.
```yaml

meta:
  env:
    MCLI_LOADER_CMD: pnpm -C ./api/ exec tsx
  watch: ./api/typegraph.ts
  command: meta deploy -f ./api/typegraph.ts --allow-dirty --create-migration --target dev

```
